name: hacker_news
description: The Hacker News app.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^5.0.0
  http: ^0.13.0
  webview_flutter: ^2.0.1
  shared_preferences: ^2.0.3
  built_collection: ^5.0.0
  built_value: ^8.0.0
  font_awesome_flutter: ^9.0.0
  rxdart: ^0.26.0
  connectivity: ^3.0.2
  share: ^2.0.0
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  google_sign_in: ^5.0.1

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^8.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/GoogleSans.ttf